name: Deploy

on:
  push:
    branches: "main"
  workflow_dispatch:
    branches: "**"
    inputs:
      server:
        description: "The server to deploy to"
        required: true
        default: "root@lxlibrary.online"

env:
  SERVER: ${{ github.event.inputs.server || 'root@lxlibrary.online' }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}

      - name: Set up known_hosts
        run: echo "${{ secrets.SERVER_SSH_PUBLIC_KEY }}" >> ~/.ssh/known_hosts

      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        run: PUBLIC_URL=/games ./scripts/deploy.sh lx-library/lx-embed-games ${{ env.SERVER }}
